export const categories = [
  "All",
  "Caves",
  "Events",
  "Parks",
  "Amusement Parks",
  "Everything Trains",
  "Farms & Markets",
  "Golf",
  "Historical Sites",
  "Indoor Recreations",
  "Museums",
  "Music & Nightlife",
  "Outdoor Recreations",
  "Parks & Trails",
  "Performing & Visual Arts",
  "Shopping",
  "Sports & Facilities",
];
export const locations = [
  {
    id: 1,
    name: "Tytoona Cave",
    description: "A beautiful natural limestone cave.",
    latitude: 40.555,
    longitude: -78.383,
    category: "Caves",
  },
  {
    id: 2,
    name: "Indian Caverns",
    description: "Historic show cave open for tours.",
    latitude: 40.6,
    longitude: -78.45,
    category: "Caves",
  },
  {
    id: 3,
    name: "Lakemont Park",
    description: "Family-friendly amusement park.",
    latitude: 40.476,
    longitude: -78.39,
    category: "Parks",
  },
  {
    id: 4,
    name: "Canoe Creek Trail",
    description: "Scenic trail through the state park.",
    latitude: 40.465,
    longitude: -78.295,
    category: "Trails",
  },
];
